#!/bin/sh -e

[ -d archive/ ] || mkdir archive/

for file in tmp/elenco_siti_inibiti.rtf tmp/blacklist.csv lista.agcom lista.manuale; do
  [ -s "$file" ] || continue

  file_name="${file##*/}"

  # rotate the file only if it different from the current one
  if cmp --quiet "$file" "archive/${file_name}.0"; then
    continue
  fi

  cp -a "$file" "archive/${file_name}"
  savelog -q -c 30 -l "archive/${file_name}"
done

