#!/bin/sh -e

. ./config.sh

if [ -z "$1" ]; then
  echo "Usage: $0 \"LISTS\"" >&2
fi
LISTS="$1"

CONF='lists/unbound.conf'

##############################################################################
list2unboundconf() {
  local list="$1"
  local ipredir="$2"

  local name

  if [ -n "$WHITELIST_FILE" ] && [ -f "$WHITELIST_FILE" ]; then
    names=$(
      grep '^[^#]' "lists/$list" |
        python3 filter-whitelist.py \
          --type domain \
          --whitelist "$WHITELIST_FILE"
    )
  else
    names=$(grep '^[^#]' "lists/$list")
  fi

  if [ "$ipredir" ]; then
    case "$ipredir" in
      *[!0-9.]*)
        for name in $names; do
          printf "\tlocal-data: \"$name CNAME $ipredir\"\n"
        done
        ;;
      *)
        for name in $names; do
          printf "\tlocal-data: \"$name A $ipredir\"\n"
        done
        ;;
    esac
  else
    for name in $names; do
      printf "\tlocal-zone: \"$name\" static\n"
    done
  fi
}

##############################################################################
# process the lists and build the final unbound.conf file
echo "server:" > $CONF.new
for list in $LISTS; do
  case "$list" in
  cncpo)    ipredir='212.25.179.125' ;;
  aams)     ipredir='sito-inibito-giochi.adm.gov.it.' ;;
  ivass)    ipredir='warning.ivass.it.' ;;
  tabacchi) ipredir='sito-inibito-tabacchi.adm.gov.it.' ;;
  manuale)  ipredir='0.0.0.0' ;;
  *)        ipredir='' ;;
  esac

  printf "\t# domains from the $list list\n"
  list2unboundconf "$list" "$ipredir"
done >> $CONF.new
