#!/bin/bash
# This script assumes a Linux system and something (like quagga) which will
# propagate as null routes the local static routes having a specific nexthop.
# It will sync these static routes with the ones in the list(s) by adding and
# removing local routes as needed.
# Set $DRY_RUN to only get a summary of the changes which would be applied.

source config.sh

BLACKHOLEFILE=$1

if [ "x$BLACKHOLEFILE" == "x" ] ; then 
	BLACKHOLEFILE=$CONF_IP
fi

if [ ! -e $BLACKHOLEFILE ] ; then 
	test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - ERROR: File $BLACKHOLEFILE not found" >> $LOGFILE
       exit
fi       

test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Install Routes Linux Started" >> $LOGFILE

NUMBER=0
while read -r line ; do
	NUMBER=$(expr $NUMBER + 1)
	# works with both ip or cidr
	ip route add $line via $BLACKHOLE_NEXTHOP
done < $BLACKHOLEFILE

test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Added $NUMBER RBH routes" >> $LOGFILE

test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Install Routes Linux Ended" >> $LOGFILE
