#!/bin/sh -e

URL_aams='ftp://ftp.finanze.it/pub/monopoli/elenco_siti_inibiti.rtf'
FILE_aams='tmp/elenco_siti_inibiti.rtf'

CURL_OPTS_aams=''

##############################################################################
# be verbose when stdout is a tty
if [ ! -t 0 ]; then
  CURL_OPTS_aams="$CURL_OPTS_aams --silent --show-error"
fi

## downloading ###############################################################
curl --fail --location --remote-time $CURL_OPTS_aams \
  --output $FILE_aams.tmp $URL_aams
mv $FILE_aams.tmp $FILE_aams

## parsing ###################################################################
./parse_aams $FILE_aams lists/aams.new

