#!/bin/bash

source config.sh

#copying files from AAIP Privacy Shield Client
test -e "$PATH_pscaiip_fqdn"   && cp $PATH_pscaiip_fqdn $FILE_pscaiip
if [ -e "$PATH_pscaiip_ipv4" ] ; then 
	cat $PATH_pscaiip_ipv4 > $FILE_pscaiip-ip
	test -e "$PATH_pscaiip_ipv6"  && cat $PATH_pscaiip_ipv6 >> $FILE_pscaiip-ip
else
	test -e "$PATH_pscaiip_ipv6" && cat $PATH_pscaiip_ipv6 > $FILE_pscaiip-ip
fi


if [ -e "$FILE_pscaiip" ]; then
  egrep '^[^#]' $FILE_pscaiip | sed 's~http[s]*://~~g' | sort | uniq > lists/pscaiip.new.tmp
  mv lists/pscaiip.new.tmp lists/pscaiip.new
   test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Imported list of FQDN  $FILE_pscaiip" >> $LOGFILE
elif [ ! -e lists/pscaiip.new ]; then
  : > lists/pscaiip.new
fi

# allow manual add of specific IPs if file exists (ex lista.pscaiip-ip)
  if [ -e $FILE_pscaiip-ip ]; then
        egrep '^[^#]' $FILE_pscaiip-ip | sort | uniq > lists/pscaiip-ip
	test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Imported list of IP  $FILE_pscaiip-ip" >> $LOGFILE
  fi

test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%M:%S') - Import pscaiip Completed" >> $LOGFILE
