#!/bin/bash
# Documented on:
# https://www1.agenziadoganemonopoli.gov.it/siti_inibiti_tabacchi.htm

source common_aams.sh

URL_aams1='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti_tabacchi/elenco_siti_inibiti.txt'
URL_aams2='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti_tabacchi/file_controllo.txt'

download_aams lists/tabacchi.new

