#!/bin/bash
# Documented on:
# https://www1.agenziadoganemonopoli.gov.it/siti_inibiti_tabacchi.htm

source common_aams.sh

BASE=""
ELENCO=$(wget -q https://www.adm.gov.it/portale/siti-inibiti-tabacchi -O - | grep txt | grep -i Elenco | cut -d\" -f2)
CONTROLLO=$(wget -q https://www.adm.gov.it/portale/siti-inibiti-tabacchi -O - | grep txt | grep -i Controllo | cut -d\" -f2)

#URL_aams1='https://www1.adm.gov.it/files_siti_inibiti/elenco_siti_inibiti.txt'
#URL_aams2='https://www1.adm.gov.it/files_siti_inibiti/file_controllo.txt'

URL_aams1="https://www.adm.gov.it$ELENCO"
URL_aams2="https://www.adm.gov.it$CONTROLLO"


#URL_aams1='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti_tabacchi/elenco_siti_inibiti.txt'
#URL_aams2='https://www1.agenziadoganemonopoli.gov.it/files_siti_inibiti_tabacchi/file_controllo.txt'

download_aams lists/tabacchi.new 

