#!/bin/bash

source config.sh
source curl_errors.sh

##############################################################################
# be verbose when stdout is a tty
if [ ! -t 0 ]; then
  CURL_OPTS_cncpo="$CURL_OPTS_cncpo --silent --show-error"
fi

# on this server, bind to a specific IP address
if [ "$(hostname --fqdn)" = "anubi.seeweb.it" ]; then
  CURL_OPTS_cncpo="$CURL_OPTS_cncpo --interface 212.25.179.125"
fi

## downloading ###############################################################
curl --fail --location --remote-time $CURL_OPTS_cncpo \
  --output $FILE_cncpo.tmp $URL_cncpo

CURL_RETURN=$?

mv $FILE_cncpo.tmp $FILE_cncpo

if [ $CURL_RETURN != 0 ] ; then
        SUBJECT="Error while fetching CNCPO lists"
        TXT="Curl on $(hostname --fqdn) have returned $CURL_RETURN:\n\n${curl_errors[$CURL_RETURN]}\n\n when trying to get $URL_cncpo."
	if [ $ALERT_ENABLE == true ] && [ "x$NOC_EMAIL" != 'x' ] ; then
        	echo -e "Subject: $SUBJECT\nFrom:$FROM_EMAIL\n$TXT" | sendmail $NOC_EMAIL
	fi
        test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%m:%S') - CNCPO Error: $TXT" >> $LOGFILE
        echo "Warning: $TXT" >&2

else
     test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%m:%S') - Successfully downloaded CNCPO lists" >> $LOGFILE

fi

## parsing ###################################################################
test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%m:%S') - CNCPO Parsing Started" >> $LOGFILE
./parse_cncpo $FILE_cncpo lists/cncpo.new lists/cncpo-ip.new 2>&1 | tee -a $LOGFILE
if [ $? == 0 ] ; then
	test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%m:%S') - CNCPO Parsing Completed" >> $LOGFILE
else
	test $LOGGING_ENABLE == true && echo "$(date '+%d/%m/%y %H:%m:%S') - Error while Parsing CNCPO Lists" >> $LOGFILE
fi

